PinedaSoftware/Models/ContactModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using PinedaSoftware.Common.ModelBinders;

namespace PinedaSoftware.Models
{
    /// <summary>
    /// Class used to model 'Contanct Me' form values.
    /// </summary>
    [ModelBinder(typeof(TrimModelBinder))]
    public class ContactModel
    {
        [Required]
        [DisplayName("Name")]
        [MaxLength(20, ErrorMessage = "Max length of 20")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Email")]
        [EmailAddress]
        [MaxLength(35, ErrorMessage = "Max length of 35")]
        public string Email { get; set; }

        [DisplayName("Phone")]
        [Phone]
        [MaxLength(13, ErrorMessage = "Max length of 13")]
        public string Phone { get; set; }
        
        [Required]
        [DisplayName("Message")]
        [MaxLength(250, ErrorMessage = "Max length of 250")]
        public string Message { get; set; }

        [MaxLength(10)]
        public string Username { get; set; }
    }
}

PinedaSoftware/Models/RequestModel.cs
using PinedaSoftware.Common.ModelBinders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PinedaSoftware.Models
{
    /// <summary>
    /// Classs used to model an HTTP context request.
    /// </summary>
    [ModelBinder(typeof (TrimModelBinder))]
    public class RequestModel
    {
        public DateTime DateTime { get; set; }
        public string IpAddress { get; set; }
        public string Browser { get; set; }
        public string BrowserVersion { get; set; }
        public bool IsMobileDevice { get; set; }
        public string MobileInformation { get; set; }
    }
}

PinedaSoftware/Controllers/AjaxController.cs
using PinedaSoftware.Helper;
using PinedaSoftware.Models;
using System.Web.Mvc;

namespace PinedaSoftware.Controllers
{
    /// <summary>
    /// Controller for Ajax actions only.
    /// </summary>
    public class AjaxController : Controller
    {
        #region Contant Email

        /// <summary>
        /// Sends email with 'Contact Me' form values using SMTP.
        /// </summary>
        /// <param name="model">'Contact Me' form object.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ContantEmail(ContactModel model)
        {
            //Bot trap
            if (!string.IsNullOrEmpty(model.Username))
                return new HttpStatusCodeResult(200);

            if(!ModelState.IsValid)
                return new HttpStatusCodeResult(400);

            if (!EmailHelper.SendEmail(model))
                return new HttpStatusCodeResult(500);

            return new HttpStatusCodeResult(200);
        }
        #endregion Contant Email
    }
}

PinedaSoftware/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PinedaSoftware.Controllers
{
    /// <summary>
    /// Controller used for Pinedasoftware landing page.
    /// </summary>
    public class HomeController : Controller
    {
        /// <summary>
        /// Landing page action.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //Set viewbag values from web.config for urls. TODO: replace viewbags with view model?
            ViewBag.Url_StackOverflow = ConfigurationManager.AppSettings["StackOverflow"];
            ViewBag.Url_LinkedIn = ConfigurationManager.AppSettings["LinkedIn"];
            ViewBag.Url_GitHub = ConfigurationManager.AppSettings["GitHub"];

            return View();
        }
    }
}

PinedaSoftware/Views/Home/Index.cshtml
@using PinedaSoftware.Models
@model ContactModel
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div id="settings" data-url-contant="@Url.Action("ContantEmail", "Ajax")">
    </div>
</div>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#top">PinedaSoftware</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item mx-0 mx-lg-1">
                    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Items</a>
                </li>
                <li class="nav-item mx-0 mx-lg-1">
                    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">About Me</a>
                </li>
                <li class="nav-item mx-0 mx-lg-1">
                    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- Masthead -->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image -->
        <img id="headShot" class="mb-5 avatar-image" src="~/Content/images/Image_Profile.jpg" alt="Noe Pineda" />
        <!-- Masthead Heading -->
        <h1 class="masthead-heading text-uppercase mb-0">Noe Pineda</h1>
        <!-- Icon Divider -->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading -->
        <p class="masthead-subheading font-weight-light mb-0">Full Stack - Software Developer</p>
    </div>
</header>
<!-- Portfolio Section -->
<section class="page-section portfolio" id="portfolio">
    <div class="container">
        <!-- Portfolio Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Items</h2>
        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Portfolio Grid Items -->
        <div class="row">
            <button type="button" class="btn btn-primary btn-lg btn-block button-vertical-padding button-horizontal-margin" data-toggle="modal" data-target="#portfolioModal1">
                <span>My Story</span> &nbsp;&nbsp;&nbsp;<img class="img-fluid image-size image-bottom-margin" src="~/Content/images/open-book.png" alt="Icons made by https://www.flaticon.com/authors/freepik" />
            </button>

            <button type="button" class="btn btn-primary btn-lg btn-block button-vertical-padding button-horizontal-margin" data-toggle="modal" data-target="#portfolioModal2">
                <span>Projects</span> &nbsp;&nbsp;&nbsp;<img class="img-fluid image-size image-bottom-margin" src="~/Content/images/start-up.png" alt="Icons made by https://www.flaticon.com/authors/freepik" />
            </button>

            <button type="button" id="github_button" class="btn btn-primary btn-lg btn-block button-vertical-padding button-horizontal-margin" data-toggle="modal">
                <span>GitHub</span> &nbsp;&nbsp;&nbsp;<img class="img-fluid image-size image-bottom-margin" src="~/Content/images/github-logo.png" alt="Icons made by https://www.flaticon.com/authors/freepik" />
            </button>

            <button type="button" id="linkedin_button" class="btn btn-primary btn-lg btn-block button-vertical-padding button-horizontal-margin" data-toggle="modal">
                <span>LinkedIn</span> &nbsp;&nbsp;&nbsp;<img class="img-fluid image-size image-bottom-margin" src="~/Content/images/linkedin-button.png" alt="Icons made by https://www.flaticon.com/authors/freepik" />
            </button>

            <button type="button" id="stackoverflow_button" class="btn btn-primary btn-lg btn-block button-vertical-padding button-horizontal-margin" data-toggle="modal">
                <span>Stack Overflow</span> &nbsp;&nbsp;&nbsp;<img class="img-fluid image-size image-bottom-margin" src="~/Content/images/stack-overflow.png" alt="Icons made by https://www.flaticon.com/authors/freepik" />
            </button>
        </div>
        <!-- /.row -->
    </div>
</section>
<!-- About Section -->
<section class="page-section bg-primary text-white mb-0" id="about">
    <div class="container">
        <!-- About Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-white">About Me</h2>
        <!-- Icon Divider -->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- About Section Content -->
        <div class="row">
            <div class="col-lg-4 ml-auto">
                <p class="lead">
                    I am a full stack software developer. I started programming 
                    for a living using the .NET Framework in 2017. I have a wide 
                    set of skills in web development e.g. web application 
                    hosting, frontend development, backend development, and 
                    database management. For hosting I have experience with IIS 
                    on Windows OS. For frontend development I have experience 
                    with HTML, CSS/Bootstrap & JavaScript/JQuery. For backend 
                    I have experience with C#. Lastly, for database management 
                    I have experience with MSSQL.
                </p>
            </div>
            <div class="col-lg-4 mr-auto">
                <p class="lead">
                    My passion for software development and self-improvement 
                    doesn’t end when I leave the office after a full day of 
                    programming. I dedicate time to learning the fundamental 
                    concepts of Computer Science such as data structures, 
                    algorithms, asymptotic notation (Big(O)), etc. I 
                    challenge myself with 
                    <a href="https://leetcode.com">LeetCode.com </a> 
                    problems to improve my problem-solving skills. I also have 
                    an associate degree in Computer Programming from Mesa 
                    Community College.
                </p>
            </div>
        </div>
        <!-- About Section Button -->
        <div class="text-center mt-4">
            <a class="btn btn-xl btn-outline-light" href="~/Content/documents/resume/Noe Pineda Resume.pdf">
                <i class="fas fa-download mr-2"></i>
                Download Resume
            </a>
        </div>
    </div>
</section>
<!-- Contact Section -->
<section class="page-section" id="contact">
    <div class="container">
        <!-- Contact Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Me</h2>
        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Contact Section Form -->
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <!--Form-->
                @Html.Partial("~/Views/Home/Partial/_Contact.cshtml", new ContactModel())

            </div>
        </div>
    </div>
</section>
<!-- Footer -->
<footer class="footer text-center">
    <div class="container">
        <div class="row">
            <!-- Footer Location -->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Location</h4>
                <p class="lead mb-0">
                    Phoenix, AZ
                    <br>85042
                </p>
            </div>
            <!-- Footer Social Icons -->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Around the Web</h4>
                <a class="btn btn-outline-light btn-social mx-1" target="_blank" href="@ViewBag.Url_StackOverflow">
                    <i class="fab fa-fw fa-linkedin-in"></i>
                </a>
                <a class="btn btn-outline-light btn-social mx-1" target="_blank" href="@ViewBag.Url_LinkedIn">
                    <i class="fab fa-fw fa-stack-overflow"></i>
                </a>
                <a class="btn btn-outline-light btn-social mx-1" target="_blank" href="@ViewBag.Url_GitHub">
                    <i class="fab fa-fw fa-github"></i>
                </a>
            </div>
            <!-- Footer About Text -->
            <div class="col-lg-4">
                <h4 class="text-uppercase mb-4">About PinedaSoftware</h4>
                <p class="lead mb-0">
                    PinedaSoftware is Powered by ASP.NET MVC and Bootstrap.
                </p>
            </div>
        </div>
    </div>
</footer>
<!-- Copyright Section -->
<section class="copyright py-4 text-center text-white">
    <div class="container">
        <small>1.0.0</small>
    </div>
</section>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-to-top d-lg-none position-fixed ">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#top">
        <i class="fa fa-chevron-up"></i>
    </a>
</div>

<!-- Portfolio Modals -->
<!-- Portfolio Modal 1 -->
<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-labelledby="portfolioModal1Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">
                    <i class="fas fa-times"></i>
                </span>
            </button>
            <div class="modal-body text-center">
                @Html.Partial("~/Views/Home/Partial/_MyStory.cshtml")
            </div>
        </div>
    </div>
</div>
<!-- Portfolio Modal 2 -->
<div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-labelledby="portfolioModal2Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">
                    <i class="fas fa-times"></i>
                </span>
            </button>
            <div class="modal-body text-center">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <!-- Portfolio Modal - Title -->
                            <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Projects</h2>
                            <!-- Icon Divider -->
                            <div class="divider-custom">
                                <div class="divider-custom-line"></div>
                                <div class="divider-custom-icon">
                                    <i class="fas fa-star"></i>
                                </div>
                                <div class="divider-custom-line"></div>
                            </div>
                            <!-- Portfolio Modal - Image -->
                            <img class="img-fluid rounded mb-5" src="~/Content/images/Code on Mac.JPG" alt="Picture of code for a personal project of mine" />
                             @*Portfolio Modal - Text*@ 
                            <p class="mb-5">
                                Comming soon.
                            </p>
                            
                            <button class="btn btn-primary" href="#" data-dismiss="modal">
                                <i class="fas fa-times fa-fw"></i>
                                Close Window
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    @Scripts.Render("~/bundles/landingPage")
    @Scripts.Render("~/bundles/contact")
}

PinedaSoftware/Views/Home/Partial/_Contact.cshtml
@using PinedaSoftware.Models;
@model ContactModel
@{
    Layout = null;
}

<!--'Contanct Me' Form-->
<form name="sentMessage" id="contactForm" novalidate="novalidate">
    <div class="control-group">
        <div class="form-group floating-label-form-group controls mb-0 pb-2">
            <label>Name</label>
            <input class="form-control" id="name" name="Name" type="text" placeholder="Name" required="required" maxlength="20" data-validation-required-message="Please enter your name.">
            <div class="help-block text-danger">
                <ul role="alert" id="name-validation-message-list"></ul>
            </div>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls mb-0 pb-2">
            <label>Email Address</label>
            <input class="form-control" id="email" name="Email" type="email" placeholder="Email Address" required="required" maxlength="35" data-validation-required-message="Please enter your email address.">
            <div class="help-block text-danger">
                <ul role="alert" id="email-validation-message-list"></ul>
            </div>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls mb-0 pb-2">
            <label>Phone Number</label>
            <input class="form-control" id="phone" name="Phone" type="tel" placeholder="Phone Number (Optional)" maxlength="13" data-validation-required-message="Please enter your phone number.">
            <div class="help-block text-danger">
                <ul role="alert" id="phone-validation-message-list"></ul>
            </div>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls mb-0 pb-2">
            <label>Message</label>
            <textarea class="form-control" id="message" name="Message" rows="5" placeholder="Message" required="required" maxlength="250" data-validation-required-message="Please enter a message."></textarea>
            <div id="message-charactersleft-counter" class="gray"></div>
            <div class="help-block text-danger">
                <ul role="alert" id="message-validation-message-list"></ul>
            </div>
        </div>
    </div>
    <div id="form-username-field">
        <label>Username</label>
        <input type="text" name="Username" id="Username" />
    </div>

    <br>
    <div id="contactFormTryAgain"></div>
    
    <!--Submit Buttons-->
    <div class="form-group" id="submit-form-group">
        <button type="submit" class="btn btn-primary btn-xl" id="sendMessageButtonDisabled" onclick="preventSubmit(event);">Fill Form To Send Message</button>
        <button type="submit" class="btn btn-primary btn-xl hide" id="sendMessageButton">Send Message</button>
    </div>
</form>

<!--'Contanct Me' Form Submitted Message-->
<div id="contactFormSubmitted">
</div>

PinedaSoftware/Views/Home/Partial/_MyStory.cshtml
@{
    Layout = null;
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <!-- Portfolio Modal - Title -->
            <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">My Story</h2>
            <!-- Icon Divider -->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Portfolio Modal - Image -->
            <img class="img-fluid rounded mb-5" src="~/Content/images/Coffee and items.JPG" alt="Picture taken at my work station a while back" />
            <!-- Portfolio Modal - Text -->
            <p class="mb-5" align="left">
                &emsp;&emsp;My journey as a software developer began at the age of 21 while on my path towards another career.
                I originally wanted to become a mechanical engineer, so naturally I began reading up on
                robotics. I figured that if I was going to become a mechanical engineer, I might as well
                learn how to build simple robots. The book I chose dedicated one of its chapters to
                software; it went on to explain how software is almost always the single most important aspect
                of any system. I dropped the book, I dropped my pursuit of mechanical engineering and I began
                to submerge myself in the world of software development. I figured that if I ever wanted to
                make a real difference in the world, I needed an efficient way to express my ideas, and I
                thought to myself, “what better way to express great ideas than through software?”. At the time
                I was working as an engineer assistant at a manufacturing facility, which I had originally been
                hired for as to be an assembly-line plumbing technician. Fortunately for me, I had already worked with the on-site
                software developer on a handful of projects. I began to seek him out and pick at his brain on
                concepts I didn't have understand; he later became my first career mentor. I began to fall
                in love with software. I couldn’t get enough of it. I would spend endless hours learning
                object-oriented programming with Java and eventually moved onto front-end development. After
                many hours of frustration and helplessness I began to gain the confidence to make the decision
                of pursuing software development as a career and not just a hobby. It was at this point that my
                mentor, at that time, decided I was ready for ASP.NET and the .NET framework. I was overwhelmed
                at first, but with time and practice I began to develop real world applications. I had been going
                to school for a few semesters before I took an interest in software development, so my classes
                were not aimed toward any software related degrees. I updated my associate degree from ‘Science’
                to ‘Computer Programming’ after my new-found passion for software. Once I had switched my degree,
                I began to sign up for software development classes such as object-oriented programming, databases,
                web development, app design, networking, and many more. My next objective was to get some sort
                experience in the field since I knew it would take more than just passion to convince someone to
                hire me as a software developer. I managed convinced the IT manager at the manufacturing facility I worked at at the time to allow
                me to work for free along side the software developer in an exchange for experience. After some time
                had gone, I ended as a system administrator and eventually landed the role of software developer in
                that same company. The IT team consisted of only one software developer, so I was all alone with no
                help. This taught me many valuable lessons one of which was how to be independent. I much rather work
                on a team since, in my opinion, this is a more enjoyable way to develop great software.
                <br />
                <br />
                &emsp;&emsp;This is the story of how I got started as a software developer. I am grateful for my career because
                I love what I do for a living and I really enjoy soliving complicated problems and making life easier through great software. 
                Software develpment is a craft and I seek to improve at my craft everyday.
            </p>
            <button class="btn btn-primary" href="#" data-dismiss="modal">
                <i class="fas fa-times fa-fw"></i>
                Close Window
            </button>
        </div>
    </div>
</div>

PinedaSoftware/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>PinedaSoftware - Making a Positive Impact</title>

    <link runat="server" rel="shortcut icon" src="~/favicon.ico" type="image/x-icon" />
    <link runat="server" rel="icon" src="~/favicon.ico" type="image/ico" />

    <meta name="description" content="Personal Website">
    <meta name="author" content="Noe Pineda">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    @Styles.Render("~/bundles/styles")
    
    <!--Not in bundle because it causes issues with font file paths.-->
    <link href="~/Content/css/all.css" rel="stylesheet" />
</head>

<body>
    <!--The original template can be found here https://startbootstrap.com/previews/freelancer -->

    <div>
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/customJS")
    @Scripts.Render("~/bundles/s")

    <!--Not in bundle because it causes issues with JS in files.-->
    <script src="~/Content/Scripts/jqBootstrapValidation.js"></script>
    <script src="~/Content/Scripts/freelancer.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>